export const Songs=[
    {
    song:"/songs/beleiver.mp3",
    cover:"/images/believer.jpeg",
    title:"Believer",
    artist:"Imagine Dragons",
},
{
    song:"/songs/bloom.mp3",
    cover:"/images/bloom.jpeg",
    title:"Bloom",
    artist:"(G)I-DLE",
},
{
    song:"/songs/bluebutterflies.mp3",
    cover:"/images/bluebutterflies.jpeg",
    title:"Blue Butterflies",
    artist:"JHIN",
},
{
    song:"/songs/cupid.mp3",
    cover:"/images/cupid.jpeg",
    title:"CUPID",
    artist:"FIFTY FIFTY",
},
{
    song:"/songs/deeperthanitseems.mp3",
    cover:"/images/deeperthanitseems.jpeg",
    title:"Deeper than it seems",
    artist:"Jace June",
},
{
    song:"/songs/dragmedown.mp3",
    cover:"/images/dragmedown.jpeg",
    title:"Drag me down",
    artist:"One Direction",
},
{
    song:"/songs/fate.mp3",
    cover:"/images/fate.jpg",
    title:"Fate",
    artist:"(G)I-DLE",
},
{
    song:"/songs/feather.mp3",
    cover:"/images/feather.jpeg",
    title:"Feather",
    artist:"Sabrina Carpenter",
},
{
    song:"/songs/idontthinkthatilikeher.mp3",
    cover:"/images/likeher.jpg",
    title:"I don't think that i like her",
    artist:"Charlie Puth",
},
{
    song:"/songs/imsixansheslikeanine.mp3",
    cover:"/images/iamsix.jpg",
    title:"I'M SIX AND SHE IS LIKE A NINE",
    artist:"Labit",
},
{
    song:"/songs/knowmetowell.mp3",
    cover:"/images/knowmetoowell.jpeg",
    title:"Know me too well",
    artist:"New Hope Club",
},
{
    song:"/songs/lassothemoon.mp3",
    cover:"/images/lassothemoon.jpeg",
    title:"Lasso the moon",
    artist:"Tiger La Flor",
},
{
    song:"/songs/lastbite.mp3",
    cover:"/images/lastbite.png",
    title:"last bite",
    artist:"Johnson",
},
{
    song:"/songs/livinginthe90s.mp3",
    cover:"/images/livinginthe90s.jpeg",
    title:"Living in the 90s",
    artist:"Tiger La Flor",
},
{
    song:"/songs/meowthestreetboy.mp3",
    cover:"/images/meow.jpeg",
    title:"Meow the street boy",
    artist:"Umji",
},
{
    song:"/songs/onthestreets.mp3",
    cover:"/images/onthestreets.jpeg",
    title:"On the streets",
    artist:"J-hope, J Cole",
},
{
    song:"/songs/senarita.mp3",
    cover:"/images/senorita.jpg",
    title:"Senorita",
    artist:"Shawn Mendes, Camilla Cabello",
},
{
    song:"/songs/sleewell.mp3",
    cover:"/images/sleepwell.jpeg",
    title:"Sleep well",
    artist:"D4vd",
},
{
    song:"/songs/sothisislove.mp3",
    cover:"/images/cinderalla.jpeg",
    title:"So this is love",
    artist:"Llene Woods",
},
{
    song:"/songs/summerdied.mp3",
    cover:"/images/sumerDied.jpeg",
    title:"Summer Died",
    artist:"Labit",
},
{
    song:"/songs/thecutestpair.mp3",
    cover:"/images/thecutestpair.jpeg",
    title:"The cutest pair",
    artist:"Regina Song",
},
{
    song:"/songs/theworstpart.mp3",
    cover:"/images/theworstpart.jpeg",
    title:"The worst part",
    artist:"Claudia,Hnata",
},
{
    song:"/songs/touch.mp3",
    cover:"/images/touch.jpg",
    title:"Touch",
    artist:"Sunkis",
},
{
    song:"/songs/wannabeyours.mp3",
    cover:"/images/wannabeyours.jpeg",
    title:"I wanna be yours",
    artist:"Arctic Monkeys",
},
{
    song:"/songs/whatifwe.mp3",
    cover:"/images/whatifwe.jpg",
    title:"What if we?",
    artist:"Emi Choi",
},
]